version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cc:c3:56:cb:e8:5f:9b:15:bb:44:e3:ba:5c:e1:43:8b"

      - run:
          name: Build
          command: cd smart-home && mvn install clean package
      - run:
          name: Scp Jar Archive to AWS
          command: scp smart-home/target*.jar $SSH_USER@$SSH_HOST:/home/ec2-user/smart_home/app.jar

      - run:
          name: Scp deploy.sh to AWS
          command: scp -o StrictHostKeyChecking=accept-new  deploy.sh $SSH_USER@$SSH_HOST:/home/ec2-user/smart_home/deploy.sh

      - run:
          command: ssh -o StrictHostKeyChecking=accept-new $SSH_USER@$SSH_HOST "cd smart_home && chmod +x deploy.sh && source deploy.sh"
          name: Run Server

workflows:
  build-and-test:
    jobs:
      - build